### ISSUE TITLE
Didn't work :-(

### ISSUE THREAD

**Issue by sporty81** [NanoTools/easy-nano-node#1]
Tried this on a brand new droplet but didn't get it to work.

root@ubuntu-s-1vcpu-2gb-nyc1-01:~# bash <(curl -s https://raw.githubusercontent.com/nanotools/easy-nano-node/master/install.sh)
== Cloning installation
fatal: Cannot change to '/opt/easy-nano-node': No such file or directory
Cloning into '/opt/easy-nano-node'...
remote: Counting objects: 100, done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 100 (delta 41), reused 71 (delta 22), pack-reused 0
Receiving objects: 100% (100/100), 12.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (41/41), done.
Checking connectivity... done.
== Starting installation
== Cloning Nano Node Monitor
fatal: Cannot change to '/opt/nanoNodeMonitor': No such file or directory
Cloning into '/opt/nanoNodeMonitor'...
remote: Counting objects: 519, done.
remote: Total 519 (delta 0), reused 0 (delta 0), pack-reused 519
Receiving objects: 100% (519/519), 1.38 MiB | 0 bytes/s, done.
Resolving deltas: 100% (297/297), done.
Checking connectivity... done.
== Updating Docker images
sudo: docker: command not found
sudo: docker: command not found
== Starting Docker containers
sudo: docker-compose: command not found
== Take a deep breath...
== Creating wallet
/opt/easy-nano-node/enn/setup.sh: line 27: docker: command not found
== Creating account
/opt/easy-nano-node/enn/setup.sh: line 30: docker: command not found
== Creating monitor config
== Modifying the monitor config
== Disabling RPC logging
sed: can't read /root/RaiBlocks/config.json: No such file or directory
== Opening Nano Node Port
Rules updated
Rules updated (v6)
== Restarting Nano node container
sudo: docker: command not found
== Just some final magic...

=== YOUR WALLET SEED ===
Please write down your wallet seed to a piece of paper and store it safely!
/opt/easy-nano-node/enn/setup.sh: line 67: docker: command not found
=== YOUR WALLET SEED ===

All done! *yay*
View your Nano Node Monitor at http://167.99.154.116

root@ubuntu-s-1vcpu-2gb-nyc1-01:~#

**Comment by sporty81** [comment]
I think you need to add to your directions to install docker first by following this: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04

**Comment by sporty81** [comment]
Still didn't work for me.

root@ubuntu-s-1vcpu-2gb-nyc1-01:~# bash <(curl -s https://raw.githubusercontent.com/nanotools/easy-nano-node/master/install.sh)
== Cloning installation
fatal: Cannot change to '/opt/easy-nano-node': No such file or directory
Cloning into '/opt/easy-nano-node'...
remote: Counting objects: 100, done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 100 (delta 41), reused 71 (delta 22), pack-reused 0
Receiving objects: 100% (100/100), 12.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (41/41), done.
Checking connectivity... done.
== Starting installation
== Cloning Nano Node Monitor
fatal: Cannot change to '/opt/nanoNodeMonitor': No such file or directory
Cloning into '/opt/nanoNodeMonitor'...
remote: Counting objects: 519, done.
remote: Total 519 (delta 0), reused 0 (delta 0), pack-reused 519
Receiving objects: 100% (519/519), 1.38 MiB | 0 bytes/s, done.
Resolving deltas: 100% (297/297), done.
Checking connectivity... done.
== Updating Docker images
Using default tag: latest
latest: Pulling from nanocurrency/nano
22dc81ace0ea: Pull complete
1a8b3c87dba3: Pull complete
91390a1c435a: Pull complete
07844b14977e: Pull complete
b78396653dae: Pull complete
ea1102c02a49: Pull complete
8a89a1ebdad1: Pull complete
104fa53ecc68: Pull complete
09fe4470750c: Pull complete
6acb82dc5b66: Pull complete
Digest: sha256:60ea9b82a45ece29f59450fd819485729741d32a458e04a29d3a8a0a010d0314
Status: Downloaded newer image for nanocurrency/nano:latest
7.2-apache: Pulling from library/php
2a72cbf407d6: Pull complete
273cd543cb15: Pull complete
ec5ac8875de7: Pull complete
9106e19b56c1: Pull complete
ee2f70ac7c7d: Pull complete
7257ad6985e8: Pull complete
18f5c2055da2: Pull complete
85293a6fdd80: Pull complete
9e797eeb0c14: Pull complete
09b55b88e646: Pull complete
2cd18314711e: Pull complete
88b610931a5f: Pull complete
b90052b881e9: Pull complete
36317e1f49af: Pull complete
6dbef1d5801a: Pull complete
Digest: sha256:1f70391aec1498d4a10b439e9fef39c3de34c872eef64af7d54152b0160b64f0
Status: Downloaded newer image for php:7.2-apache
== Starting Docker containers
sudo: docker-compose: command not found
== Take a deep breath...
== Creating wallet
Error: No such container: enn_nanonode_1
== Creating account
Error: No such container: enn_nanonode_1
== Creating monitor config
== Modifying the monitor config
== Disabling RPC logging
sed: can't read /root/RaiBlocks/config.json: No such file or directory
== Opening Nano Node Port
Rules updated
Rules updated (v6)
== Restarting Nano node container
Error response from daemon: No such container: enn_nanonode_1
== Just some final magic...

=== YOUR WALLET SEED ===
Please write down your wallet seed to a piece of paper and store it safely!
Error: No such container: enn_nanonode_1
=== YOUR WALLET SEED ===

All done! *yay*
View your Nano Node Monitor at http://167.99.154.116

**Comment by BitDesert** [comment]
Seems that docker-compose is not installed: https://docs.docker.com/compose/install/
