### ISSUE TITLE
No node monitor IP address

### ISSUE THREAD

**Issue by ppeach** [NanoTools/easy-nano-node#4]
Finally got it working it seems by installing docker-compose first as mentioned in other ticket, but now there is no Ip address for the node monitor (see bottom)

Ubuntu EC2 instance

root@ip-172-31-4-62:~# bash <(curl -s https://raw.githubusercontent.com/nanotools/easy-nano-node/master/install.sh)
== Cloning installation
fatal: Cannot change to '/opt/easy-nano-node': No such file or directory
Cloning into '/opt/easy-nano-node'...
remote: Counting objects: 137, done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 137 (delta 65), reused 97 (delta 36), pack-reused 0
Receiving objects: 100% (137/137), 17.87 KiB | 0 bytes/s, done.
Resolving deltas: 100% (65/65), done.
Checking connectivity... done.
== Starting installation
== Cloning Nano Node Monitor
fatal: Cannot change to '/opt/nanoNodeMonitor': No such file or directory
Cloning into '/opt/nanoNodeMonitor'...
remote: Counting objects: 566, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 566 (delta 16), reused 22 (delta 9), pack-reused 525
Receiving objects: 100% (566/566), 1.40 MiB | 443.00 KiB/s, done.
Resolving deltas: 100% (317/317), done.
Checking connectivity... done.
== Updating Docker images
Using default tag: latest
latest: Pulling from nanocurrency/nano
22dc81ace0ea: Pull complete
1a8b3c87dba3: Pull complete
91390a1c435a: Pull complete
07844b14977e: Pull complete
b78396653dae: Pull complete
ea1102c02a49: Pull complete
8a89a1ebdad1: Pull complete
104fa53ecc68: Pull complete
09fe4470750c: Pull complete
6acb82dc5b66: Pull complete
Digest: sha256:60ea9b82a45ece29f59450fd819485729741d32a458e04a29d3a8a0a010d0314
Status: Downloaded newer image for nanocurrency/nano:latest
7.2-apache: Pulling from library/php
2a72cbf407d6: Pull complete
273cd543cb15: Pull complete
ec5ac8875de7: Pull complete
9106e19b56c1: Pull complete
ee2f70ac7c7d: Pull complete
7257ad6985e8: Pull complete
18f5c2055da2: Pull complete
85293a6fdd80: Pull complete
9e797eeb0c14: Pull complete
09b55b88e646: Pull complete
2cd18314711e: Pull complete
88b610931a5f: Pull complete
b90052b881e9: Pull complete
36317e1f49af: Pull complete
6dbef1d5801a: Pull complete
Digest: sha256:1f70391aec1498d4a10b439e9fef39c3de34c872eef64af7d54152b0160b64f0
Status: Downloaded newer image for php:7.2-apache
== Starting Docker containers
Creating network "enn_default" with the default driver
Creating enn_nanonode_1 ... done
Creating enn_monitor_1  ... done
== Take a deep breath...
== Creating wallet
== Creating account
== Creating monitor config
== Modifying the monitor config
== Disabling RPC logging
== Opening Nano Node Port
Rules updated
Rules updated (v6)
== Restarting Nano node container
enn_nanonode_1
== Just some final magic...

=== YOUR WALLET SEED ===
Please write down your wallet seed to a piece of paper and store it safely!
Seed: [redacted]
Pub: [redacted]
=== YOUR WALLET SEED ===

All done! *yay*
View your Nano Node Monitor at http://

root@ip-172-31-4-62:~#

**Comment by BitDesert** [comment]
Can you post or PM me the output of `ifconfig`?

The setup tries to get the server IP via:

    ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -vE '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.|127\.0\.0\.1)'

Maybe we can get a better way to get the IP, that's probably unreliable sometimes.

**Comment by ppeach** [comment]
root@ip-172-31-4-62:~# ifconfig
br-33a677fd6ce9 Link encap:Ethernet  HWaddr 02:42:47:64:85:e1
          inet addr:172.18.0.1  Bcast:172.18.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:47ff:fe64:85e1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:15616742 errors:0 dropped:0 overruns:0 frame:0
          TX packets:40290381 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1194799170 (1.1 GB)  TX bytes:19312703079 (19.3 GB)

docker0   Link encap:Ethernet  HWaddr 02:42:39:f9:a6:01
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 02:52:2e:85:1d:a2
          inet addr:172.31.4.62  Bcast:172.31.15.255  Mask:255.255.240.0
          inet6 addr: fe80::52:2eff:fe85:1da2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:41639261 errors:0 dropped:0 overruns:0 frame:0
          TX packets:15617403 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:19125219739 (19.1 GB)  TX bytes:1407833901 (1.4 GB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:192 errors:0 dropped:0 overruns:0 frame:0
          TX packets:192 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:14456 (14.4 KB)  TX bytes:14456 (14.4 KB)

veth00091f6 Link encap:Ethernet  HWaddr 0a:07:c0:96:dd:b5
          inet6 addr: fe80::807:c0ff:fe96:ddb5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13055 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18424 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1371753 (1.3 MB)  TX bytes:36957991 (36.9 MB)

veth7ddbad4 Link encap:Ethernet  HWaddr a6:05:25:1c:e6:86
          inet6 addr: fe80::a405:25ff:fe1c:e686/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8495 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:2482917 (2.4 MB)

**Comment by BitDesert** [comment]
Changed the IP query to `ip route get 8.8.8.8 | awk '{ print $NF; exit }'`
