### ISSUE TITLE
Sync failed, node down

### ISSUE THREAD

**Issue by cryptomoosh** [NanoTools/easy-nano-node#5]
Got to about 400k block_count then stuck there for hours then monitor suggests it is now not running.  Restarting the container does not work:

Error response from daemon: Cannot restart container enn_nanonode_1: Cannot kill container 6bcb6296de6e03c146f59d5845480da40b299c65252e4fcb34ed6d06f0a919ee: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown

Any suggestions?

Many thanks

**Comment by BitDesert** [comment]
But `docker ps` works?

**Comment by cryptomoosh** [comment]
Yes

**Comment by BitDesert** [comment]
I would suggest a docker service or host restart, that's not an issue of the Nano Node.
